[build]
  command = "npm run build"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "18"

# Local development via `netlify dev`
[dev]
  framework = "vite"
  command = "vite"
  port = 3000
  targetPort = 3000
  autoLaunch = false

# Single Page App fallback so client-side routing works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache immutable build assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure the main HTML is always revalidated
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Basic security hardening headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"


